import { useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import Header from '../components/Header.jsx'
import Footer from '../components/Footer.jsx'

const mathFont = {
  fontFamily: '"Cambria Math", "STIX Two Math", "Latin Modern Math", Cambria, "Times New Roman", serif',
}

function Math({ children }) {
  return (
    <span
      className="inline-block rounded bg-slate-100 px-1.5 py-0.5 text-[0.95em] text-slate-900"
      style={mathFont}
    >
      {children}
    </span>
  )
}

function Equation({ children }) {
  return (
    <div className="my-6 flex justify-center">
      <div
        className="rounded-lg border border-slate-200 bg-white/80 px-8 py-5 text-center text-xl text-slate-900 shadow-sm"
        style={mathFont}
      >
        {children}
      </div>
    </div>
  )
}

function SectionDivider() {
  return (
    <div className="my-20 flex justify-center" aria-hidden="true">
      <div className="h-px w-24 bg-orange-500/60" />
    </div>
  )
}

function ScrollToHash() {
  const { hash } = useLocation()
  useEffect(() => {
    if (!hash) return
    const id = hash.replace('#', '')
    const el = document.getElementById(id)
    if (el) {
      requestAnimationFrame(() => {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' })
      })
    }
  }, [hash])
  return null
}

const problems = [
  {
    id: 'complex-exponent',
    title: 'The Complex Exponent Unification',
    figure: {
      src: '/assets/publications/complex.jpg',
      alt:
        'Bitcoin price trajectory visualized as a complex power law: the long-term trend in red, real price in blue, and log-periodic oscillations from the imaginary component shown in the complex plane.',
      caption: (
        <>
          Figure: <span style={mathFont}>P(t) = A · t<sup>(β+iω)</sup></span>. The long-term trajectory{' '}
          <span style={mathFont}>t<sup>β</sup></span> (red), the real price (blue), and the log-periodic oscillations
          generated by the imaginary component, shown in real, imaginary, and complex-plane projections.
        </>
      ),
    },
    body: (
      <>
        <p>
          Bitcoin's long-term price trajectory is well described by the real power law{' '}
          <Math>P(t) ~ t<sup>β</sup></Math> with <Math>β ≈ 5.7</Math> (Santostasi &amp; Perrenod, 2026). Its
          intermediate-scale bubble and crash structure is well described by Sornette's log-periodic power law
          singularity model, in which price exhibits oscillations of the form{' '}
          <Math>cos(ω · ln t)</Math> superposed on an accelerating trend (Wheatley et al., 2019). These two models have
          been treated as complementary but separate descriptions of different regimes.
        </p>
        <p>
          The Institute proposes that they are instead two projections of a single underlying object: a power law with
          a complex exponent.
        </p>
        <Equation>
          P(t) = A · t<sup>(β + iω)</sup>
        </Equation>
        <p>
          The real part of this expression in the time domain recovers the long-term trajectory; the imaginary part
          generates the log-periodic bubble structure; and the full trajectory in the complex plane encodes the mutual
          phase relationship between trend and oscillation. In this formulation, the long-term power law and the
          log-periodic bubble dynamics are not two phenomena that happen to coexist — they are the real and imaginary
          components of a single analytic object.
        </p>
      </>
    ),
    questions: [
      <>
        Does the empirical data support a single complex-exponent formulation, or do the real and imaginary components
        drift independently over time?
      </>,
      <>
        What is the physical interpretation of <Math>ω</Math> — is it a fundamental network frequency, a decoration of
        the underlying adoption dynamics, or a resonance between block production and adoption cycles?
      </>,
      <>
        Can the relationship between <Math>β</Math> and <Math>ω</Math> be derived from first principles, in the way
        that <Math>β</Math> itself has been derived as{' '}
        <Math>β = β<sub>A</sub> × β<sub>M</sub></Math> (address exponent × Metcalfe exponent)?
      </>,
    ],
    status: 'Actively pursued by Institute researchers.',
  },
  {
    id: 'metcalfe-exponent',
    title: 'Derivation of the Metcalfe Exponent from First Principles',
    body: (
      <p>
        The Institute's mechanistic derivation of Bitcoin's price exponent relies on the empirical relation{' '}
        <Math>P ~ N<sup>1.838</sup></Math>, a generalised Metcalfe-type scaling with an exponent measurably greater
        than 2 (Santostasi &amp; Perrenod, 2026). Classical Metcalfe's law predicts exponent 2 (pairwise connections);
        Reed's law predicts exponentially larger values for group formation; empirical studies of communication
        networks typically find values in the range 1.5–2 (Briscoe, Odlyzko &amp; Tilly, 2006). Bitcoin's measured
        value of 1.838 sits within this range but does not match any single theoretical prediction.
      </p>
    ),
    questions: [
      <>
        Is Bitcoin's Metcalfe exponent derivable from its specific network topology — scale-free with heavy-tailed
        degree distribution — rather than being an empirical constant?
      </>,
      <>
        Can the value be predicted from the distribution of transaction frequencies across Bitcoin addresses, in the
        manner that network value has been derived from usage heterogeneity in other communication systems?
      </>,
    ],
    status: 'Open for collaboration. The problem is more a challenge in network theory than in Bitcoin per se.',
  },
  {
    id: 'hash-rate-feedback',
    title: 'The Hash Rate Feedback Loop Closure',
    body: (
      <p>
        Bitcoin's hash rate scales as the square of price (<Math>H ~ P<sup>2</sup></Math>), one of the most stable
        empirical regularities in the system. The mechanism is understood qualitatively: higher prices attract more
        miners, whose competition raises the hash rate until the marginal cost of production equals the market price.
        But this qualitative story does not predict the specific exponent of 2 — it could, a priori, be anywhere from 1
        to 3 depending on assumptions about mining efficiency distributions, energy costs, and hardware obsolescence
        rates.
      </p>
    ),
    questions: [
      <>
        Can the hash-rate-to-price exponent of 2 be derived from a mining-industry cost-structure model, or is it a
        universal signature of a specific economic equilibrium that has not yet been identified?
      </>,
      <>
        How sensitive is the exponent to the distribution of electricity prices across mining regions, and should we
        expect the exponent to drift as mining geography shifts?
      </>,
    ],
    status:
      'Actively pursued by SBI Vice-Director Stephen Perrenod in the context of the semi-annual Bitcoin Mining Industry Report.',
  },
  {
    id: 'universality-class',
    title: 'The Universality Class of Bitcoin',
    body: (
      <p>
        Self-organized critical systems fall into universality classes — broad categories whose members share critical
        exponents regardless of microscopic detail. Sandpile models, directed percolation, branching processes, and the
        Ising model in various dimensions are classical examples. The proposition that Bitcoin belongs to a specific
        universality class is implicit in the Power Law Theory (Santostasi, 2026), but no identification with a known
        class has been rigorously established.
      </p>
    ),
    questions: [
      <>Which universality class, if any, contains Bitcoin?</>,
      <>
        Specifically: can Bitcoin's critical exponents (<Math>β ≈ 5.7</Math> in time;{' '}
        <Math>β<sub>A</sub> ≈ 3.05</Math> for addresses; <Math>β<sub>M</sub> ≈ 1.84</Math> for value) be matched to a
        known set of critical exponents from an established physical or mathematical model?
      </>,
    ],
    status:
      'Open for collaboration. The problem bridges statistical physics, network science, and complexity theory.',
  },
  {
    id: 'phase-structure',
    title: 'Phase Structure of Bitcoin Adoption',
    body: (
      <p>
        The preprint <em>A Mechanistic Derivation of the Bitcoin Price Power Law</em> establishes that adoption
        (measured as non-zero-balance addresses) follows <Math>N(t) ~ t<sup>3.046</sup></Math>. Cubic scaling in the
        count of a spreading process on a heterogeneous scale-free network is consistent with specific regimes of
        epidemic models, but the correspondence has not been fully characterized for Bitcoin's specific network
        structure and time scales.
      </p>
    ),
    questions: [
      <>Is Bitcoin's cubic adoption growth a transient regime, or does it persist asymptotically?</>,
      <>
        Are there observable phase transitions — changes in the scaling exponent — corresponding to qualitatively
        distinct stages of adoption (retail, institutional, sovereign), and if so, can these be predicted from the
        network's internal dynamics or only from external economic inputs?
      </>,
    ],
    status: 'Actively pursued.',
  },
  {
    id: 'falsifiability',
    title: 'The Limits of Falsifiability',
    body: (
      <p>
        The Power Law Theory makes specific falsifiable predictions: that price will continue to track{' '}
        <Math>t<sup>β</sup></Math>, that addresses will continue to track <Math>t<sup>β<sub>A</sub></sup></Math>, that
        the consistency identity <Math>β ≈ β<sub>A</sub> × β<sub>M</sub></Math> will hold. Each of these conditions
        has held through sixteen years of data including four halvings, multiple exchange collapses, regulatory
        actions, and sovereign adoption events. A rigorous treatment of the theory must specify the conditions under
        which it would be falsified, and estimate how far observed data could deviate from the predictions before the
        theory should be abandoned.
      </p>
    ),
    questions: [
      <>
        What is the appropriate falsification criterion? Specifically: given the observed residual variance, at what
        deviation magnitude should one conclude that the power law has broken rather than that the deviation is within
        the expected noise envelope?
      </>,
      <>
        How long a violation must persist before it should be interpreted as a structural change in Bitcoin's dynamics
        rather than a transient anomaly?
      </>,
    ],
    status:
      'Discussed in the Institute\'s preprint and in The Physics of Bitcoin; a formal statistical treatment remains an open theoretical problem.',
  },
]

function ProblemSection({ problem, index }) {
  return (
    <section id={problem.id} className="scroll-mt-28">
      <p className="text-xs uppercase tracking-[0.2em] text-orange-600 font-semibold mb-3 font-mono">
        Problem {index + 1}
      </p>
      <h2 className="font-serif text-3xl md:text-4xl font-semibold text-slate-900 mb-6 leading-tight">
        {problem.title}
      </h2>

      {problem.figure && (
        <figure className="my-6">
          <img
            src={problem.figure.src}
            alt={problem.figure.alt}
            className="w-full max-w-3xl mx-auto rounded-lg shadow-lg"
          />
          <figcaption className="mt-3 text-sm italic text-slate-500 text-center">
            {problem.figure.caption}
          </figcaption>
        </figure>
      )}

      <div className="space-y-4 text-slate-700 text-[1.05rem] leading-relaxed">
        {problem.body}
      </div>

      <h3 className="font-serif text-lg font-semibold text-slate-900 mt-8">Open questions:</h3>
      <ul className="list-disc pl-6 space-y-2 mt-3 text-slate-700 leading-relaxed">
        {problem.questions.map((q, i) => (
          <li key={i}>{q}</li>
        ))}
      </ul>

      <p className="mt-6 text-sm italic text-slate-600">
        <span className="font-semibold not-italic text-slate-700">Status:</span> {problem.status}
      </p>
    </section>
  )
}

export default function OpenProblems() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Header />
      <ScrollToHash />

      <main className="pt-28 pb-24">
        {/* Page title */}
        <section className="max-w-4xl mx-auto px-6 text-center">
          <p className="text-xs uppercase tracking-[0.25em] text-orange-600 font-semibold mb-4 font-mono">
            Scientific Bitcoin Institute &nbsp;·&nbsp; Research
          </p>
          <h1 className="font-serif text-5xl md:text-6xl font-semibold text-slate-900 leading-tight">
            Open Problems in Bitcoin Science
          </h1>
        </section>

        {/* Intro */}
        <section className="max-w-3xl mx-auto mt-10 px-6">
          <p className="text-slate-700 text-base leading-relaxed">
            The Scientific Bitcoin Institute maintains a living catalogue of open problems — questions that remain
            unresolved or incompletely answered within the Institute's research program and the broader scientific
            literature on Bitcoin. These are not rhetorical questions. Each is a specific, tractable problem that
            admits of mathematical, empirical, or computational progress, and each is actively pursued by Institute
            researchers or offered as an invitation to external collaborators. This page will grow as problems are
            resolved, refined, or newly identified.
          </p>
        </section>

        {/* Table of Contents */}
        <nav
          aria-label="Open problems"
          className="max-w-3xl mx-auto mt-12 px-6"
        >
          <div className="rounded-lg border border-slate-200 bg-white px-6 py-5 shadow-sm">
            <p className="text-xs uppercase tracking-wider text-slate-500 font-semibold mb-3">
              Contents
            </p>
            <ol className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-700">
              {problems.map((problem, i) => (
                <li key={problem.id} className="flex items-center gap-2">
                  <span className="text-orange-500 font-mono text-xs">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <a
                    href={`#${problem.id}`}
                    className="hover:text-orange-600 transition-colors"
                  >
                    {problem.title}
                  </a>
                </li>
              ))}
            </ol>
          </div>
        </nav>

        <SectionDivider />

        {/* Problem sections */}
        <div className="max-w-3xl mx-auto px-6">
          {problems.map((problem, i) => (
            <div key={problem.id}>
              <ProblemSection problem={problem} index={i} />
              {i < problems.length - 1 && <SectionDivider />}
            </div>
          ))}
        </div>

        <SectionDivider />

        {/* Closing */}
        <section className="max-w-2xl mx-auto px-6 text-center mt-16">
          <h3 className="font-serif text-2xl font-semibold text-slate-900 mb-4">
            Contribute to Institute research
          </h3>
          <p className="text-slate-600 leading-relaxed">
            Researchers interested in pursuing any of these open problems — whether as part of a sponsored engagement,
            a collaborative publication, or independent work — are invited to contact the Institute.
          </p>

          <div className="mt-8 flex justify-center">
            <Link
              to="/about/contact"
              className="inline-flex items-center justify-center border border-slate-300 text-slate-700 rounded px-5 py-2.5 font-semibold text-sm hover:border-slate-500 transition-colors"
            >
              Contact the Institute
            </Link>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
